require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.autocommands")
require("user.cmp")
require("user.colourscheme")
require("user.lsp")
require("user.treesitter")
require("user.telescope")
require("user.harpoon")
require("user.cybu")
require("user.autopairs")
require("user.comment")
require("user.nvim-tree")
require("user.aerial")
require("user.lualine")
require("user.toggleterm")
require("user.project")
require("user.impatient")
require("user.illuminate")
require("user.indentline")
require("user.navic")
require("user.alpha")
require("user.functions")
require("user.whichkey")
require("user.quickscope")
require("user.colorizer")
require("user.notify")
require("user.winbar")
require("user.glow")
require("user.copilot")

-- require("user.obsidian")
--require("user.dap")
--require("user.sniprun")
--full replace
