#!/bin/sh
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
export PATH=$HOME/.fnm:$PATH
export PATH="$PATH:./node_modules/.bin"

# fnm
export PATH=/home/bob/programs/fnm:$PATH
eval "$(fnm env --use-on-cd)"

# zoxide
eval "$(zoxide init zsh)"

# lf
[ -f ~/.config/lf/icons ] && {
	LF_ICONS="$(tr '\n' ':' <~/.config/lf/icons)" \
		&& export LF_ICONS
}

# turso
export PATH="/home/bob/.turso:$PATH"

source "${XDG_CONFIG_HOME:-$HOME/.config}/lf-shellcd/lf-shellcd"

# pnpm
export PNPM_HOME="/home/bob/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

# aws
export PATH=$PATH:/home/bob/Work/KJR/datarwe/aws_scripts

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/mnt/BigBoy/Work/Propel/google-cloud-sdk/path.zsh.inc' ]; then . '/mnt/BigBoy/Work/Propel/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/mnt/BigBoy/Work/Propel/google-cloud-sdk/completion.zsh.inc' ]; then . '/mnt/BigBoy/Work/Propel/google-cloud-sdk/completion.zsh.inc'; fi
